service: teste-tecnico-leve-saude

provider:
  name: aws
  runtime: nodejs22.x
  region: sa-east-1
  stage: dev
  memorySize: 128
  timeout: 30
  environment:
    NODE_ENV: ${self:provider.stage}

plugins:
  - serverless-offline
  - serverless-prune-plugin

package:
  individually: true

functions:
  getAgendas:
    handler: src/agenda/controller/agendaController.getAgendas
    events:
      - http:
          path: agendas
          method: get
  
  createAgendamento:
    handler: src/agendamento/controller/agendamentoController.createAgendamento
    events:
      - http:
          path: agendamento
          method: post

custom:
  esbuild:
    bundle: true
    minify: true
    sourcemap: true
    exclude: ['aws-sdk']
    target: 'node22'
    platform: 'node'
    external: ['@aws-sdk']
    packager: 'npm'